version: '3.4'

services:
  shoppingcart.cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    container_name: CartAPI
    ports:
    - 8001:80
    expose:
    - 8001
    build:
      context: .
      dockerfile: ShoppingCart.Cart.API/Dockerfile
  shoppingcart.discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    container_name: DiscountAPI
    ports:
    - 8002:80
    expose:
    - 8002
    build:
      context: .
      dockerfile: ShoppingCart.Discount.API/Dockerfile
  shoppingcart.order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    container_name: OrderAPI
    ports:
    - 8003:80
    expose:
    - 8003
    build:
      context: .
      dockerfile: ShoppingCart.Order.API/Dockerfile
  shoppingcart.payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    container_name: PaymentAPI
    ports:
    - 8004:80
    expose:
    - 8004
    build:
      context: .
      dockerfile: ShoppingCart.Payment.API/Dockerfile
  shoppingcart.product.api:
    image: ${DOCKER_REGISTRY-}productapi
    container_name: ProductAPI
    ports:
    - 8005:80
    expose:
    - 8005
    build:
      context: .
      dockerfile: ShoppingCart.Product.API/Dockerfile
  shoppingcart.user.api:
    image: ${DOCKER_REGISTRY-}userapi
    container_name: UserAPI
    ports:
    - 8006:80
    expose:
    - 8006
    build:
      context: .
      dockerfile: ShoppingCart.User.API/Dockerfile